services:
  app:
    build: .
    container_name: autobooking_app
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --reload
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - autobooking_network
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
      - ./data:/app/data

networks:
  autobooking_network:
    driver: bridge
