"""manager_role

Revision ID: 7dee48e42e24
Revises: 2b63ffb2c681
Create Date: 2026-04-16 08:49:50.808860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dee48e42e24'
down_revision: str | None = '2b63ffb2c681'
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'manager'")
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('company_creation_requests',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('requested_category', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='companyrequeststatus'), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_creation_requests_approved_by_id'), 'company_creation_requests', ['approved_by_id'], unique=False)
    op.create_index(op.f('ix_company_creation_requests_city'), 'company_creation_requests', ['city'], unique=False)
    op.create_index(op.f('ix_company_creation_requests_company_id'), 'company_creation_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_creation_requests_owner_id'), 'company_creation_requests', ['owner_id'], unique=False)
    op.create_index(op.f('ix_company_creation_requests_requested_category'), 'company_creation_requests', ['requested_category'], unique=False)
    op.add_column('companies', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index('ix_companies_category', table_name='companies')
    op.create_index(op.f('ix_companies_category_id'), 'companies', ['category_id'], unique=False)
    op.create_foreign_key("fk_companies_category_id_categories", 'companies', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('companies', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint("fk_companies_category_id_categories", 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_category_id'), table_name='companies')
    op.create_index('ix_companies_category', 'companies', ['category'], unique=False)
    op.drop_column('companies', 'category_id')
    op.drop_index(op.f('ix_company_creation_requests_requested_category'), table_name='company_creation_requests')
    op.drop_index(op.f('ix_company_creation_requests_owner_id'), table_name='company_creation_requests')
    op.drop_index(op.f('ix_company_creation_requests_company_id'), table_name='company_creation_requests')
    op.drop_index(op.f('ix_company_creation_requests_city'), table_name='company_creation_requests')
    op.drop_index(op.f('ix_company_creation_requests_approved_by_id'), table_name='company_creation_requests')
    op.drop_table('company_creation_requests')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
