"""unique_key_booking

Revision ID: b34b44edd490
Revises: 5c7a9d1e2f30
Create Date: 2026-04-16 14:21:51.133022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34b44edd490'
down_revision: str | None = '5c7a9d1e2f30'
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('uq_bookings_user_service_company_start_at_active', 'bookings', ['user_id', 'service_id', 'company_id', 'start_at'], unique=True, postgresql_where=sa.text("status <> 'cancelled'"))
    # ### end Alembic commands ###
    ...


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('uq_bookings_user_service_company_start_at_active', table_name='bookings', postgresql_where=sa.text("status <> 'cancelled'"))
    # ### end Alembic commands ###
    ...